### ISSUE TITLE
policy package status in Installation targets

### ISSUE THREAD

**Issue by bartdorlandt** [akshaymane920/pyFortimanagerAPI#11]
Hi, 

I've been working on some automation on the fortimanager as well, though I'm struggling to read the "Policy Package Status" from the installation targets view using the API.

Have you had any luck finding where this could be retrieved?

Thanks in advance. 
Cheers, 
Bart

**Comment by ralle12345** [comment]
Hi @bartdorlandt
I took a look at the API docs, but couldn't find any API call for that either.
Best,
Ralph

**Comment by bartdorlandt** [comment]
There is a hidden/undocumented option. I don't have access to it atm.

Along the lines of /firewall/_pkg/status.

Please have a try with that. I'll be back in 3 weeks...

**Comment by ralle12345** [comment]
Yes, you are right. The correct payload is

````
{
    "method": "get",
    "params": [{
        "url": "/pm/config/adom/root/_package/status"
    }],﻿
    "id": 1,
    "verbose": 1,
    "session": "<redacted>"
} 
````

With the url being one of

* pm/config/adom/<adom>/_package/status (all Policy Packages)
* pm/config/a﻿dom/<adom>/pkg/<pkg>/_package/s﻿tatus (specific Policy Package)
* p﻿m/config/adom/<adom>/_package/status/<de﻿vice>/<vdom> (specifig device/vdom)

And by the way I thought you were looking for the corect API call to accomplish the above :)

**Comment by akshaymane920** [comment]
Hello Team,
I found something
Url = /gui/adoms/adomname/devices/assignedpkgs
Method=get

The output results in all the packages assigned to the respective devices
and their status.

Regards
Akshay Mane

**Comment by bartdorlandt** [comment]
@ralle12345 , back from vacation and wrote it in a tweet :)
https://twitter.com/BartOmation/status/1554028688194379776

The URL I used is: "/pm/config/adom/{ADOM}/_package/status/{fgt_name}/{vdom}".

this will give back 4 keys:
dev, pkg, status, vdom.

the status options are ["imported", "installed", "never installed", "modified", "out-of-sync", "conflict", "unknown"]
