### ISSUE TITLE
exit() on login fail

### ISSUE THREAD

**Issue by Ponysmallhorse** [akshaymane920/pyFortimanagerAPI#7]
Can I recommend removing exit() call in the event of login failure?
Currently, it is impossible to use this in my scripts in this state. In case credentials changed, my service scripts are exiting execution.
In general, it is bad practice to call exit()/sys.exit() in library packages. 
Thank you.

**Comment by akshaymane920** [comment]
Hello @Ponysmallhorse ,
First of all thanks for using the module. 
Coming to the issue I think I didn't understood your question. 

My thought process to introduce exit() was if at all we login with incorrect creds that module should return an error message and get out of the loop instead returning an invalid session with no session id which will then lead to bugs in further actions.

**Comment by akshaymane920** [comment]
Hello @Ponysmallhorse,
Did some changes in Login Method (release 0.1.6). Looks good now. Can you test?
